// Updated frontend/utils/fieldMapper.ts
export const fieldMapper = {
  "نقاط قوت درسی": "academicStrengths",
  "نقاط ضعف درسی": "academicWeaknesses",
  "علاقه‌مندی‌های درسی": "academicInterests",
  "رشته مورد علاقه برای ادامه تحصیل": "preferredMajor",
  "وضعیت انضباطی": "disciplineStatus",
  "ساعات مطالعه روزانه": "dailyStudyHours",
  "فعالیت‌های فوق برنامه (المپیاد، کلاس زبان، ورزش و ...)": "extraActivities",
  "نیاز به کلاس تقویتی": "needsTutoring",
  "سطح همکاری در کلاس": "classParticipation",
  "وضعیت تکالیف و پروژه‌ها": "homeworkStatus",
  "مهارت‌های یادگیری (یادداشت‌برداری، خلاصه‌نویسی و ...)": "learningSkills",
  "توضیحات تکمیلی مشاور تحصیلی": "advisorNotes",
  "نتیجه نهایی مشاور تحصیلی (پذیرش/عدم پذیرش)": "advisorDecision",
  "مدارک تحصیلی ارائه‌شده": "submittedDocuments",
  "کارنامه سال گذشته": "lastYearReport",
  "نمره دروس اصلی (ریاضی، علوم، ادبیات، زبان)": "coreSubjectsScore",
  "حضور و غیاب در مدارس قبلی": "attendanceHistory",
  "وضعیت انتقالی یا تغییر مدرسه": "transferStatus",
  "سطح زبان خارجی": "foreignLanguageLevel",
  "میزان مشارکت در فعالیت‌های کلاسی": "classEngagement",
  "مشکلات آموزشی پیشین": "pastIssues",
  "نیاز به امکانات آموزشی خاص (کتاب، ابزار و ...)": "specialRequirements",
  "پیشنهاد برای کلاس‌بندی": "classPlacementSuggestion",
  "وضعیت سوابق تحصیلی در سال‌های قبل": "academicHistory",
  "توضیحات تکمیلی معاون آموزشی": "deputyNotes",
  "نتیجه نهایی معاون آموزشی (پذیرش/عدم پذیرش)": "deputyDecision",
  "وضعیت خانواده (شغلی، اقتصادی، فرهنگی)": "familyStatus",
  "وضعیت سکونت (نزدیکی به مدرسه، خوابگاه و ...)": "residenceStatus",
  "تعامل والدین با مدرسه": "parentCooperation",
  "توانایی‌های ویژه دانش‌آموز": "specialTalents",
  "نیازهای خاص (سلامتی، مالی، آموزشی)": "specialNeeds",
  "اهداف خانواده از ثبت‌نام": "familyGoals",
  "پیشینه حضور در مدارس دیگر": "schoolHistory",
  "تصویر کلی از رفتار اجتماعی": "socialBehavior",
  "ارزیابی کلی مدیر از دانش‌آموز": "principalEvaluation",
  "توضیحات تکمیلی مدیر": "principalNotes",
  "نتیجه نهایی مدیر (پذیرش/عدم پذیرش)": "principalDecision",
  "وضعیت روحی/روانی کلی": "mentalStatus",
  "سطح اعتماد به نفس": "confidenceLevel",
  "سطح اضطراب و استرس": "stressLevel",
  "مهارت‌های اجتماعی": "socialSkills",
  "ارتباط با همسالان": "peerRelations",
  "ارتباط با والدین": "parentRelations",
  "مشکلات خانوادگی احتمالی": "familyIssues",
  "سابقه مراجعه به مشاور یا روانپزشک": "counselingHistory",
  "مشکلات رفتاری احتمالی": "behaviorIssues",
  "نقاط قوت شخصیتی": "personalityStrengths",
  "سبک یادگیری ترجیحی (دیداری، شنیداری، عملی)": "learningStyle",
  "میزان انگیزه برای تحصیل": "studyMotivation",
  "توصیه‌های مشاور روانشناسی": "psychNotes",
  "نتیجه نهایی مشاور روانشناسی (پذیرش/عدم پذیرش)": "psychDecision",
  "سابقه انضباطی در مدارس قبلی": "pastDisciplinaryRecords",
  "گزارش‌های انضباطی سال گذشته": "lastYearDisciplinaryReport",
  "وضعیت رفتار در کلاس": "classBehavior",
  "حوادث گزارش‌شده": "reportedIncidents",
  "درگیری با همکلاسی‌ها": "peerConflicts",
  "رعایت قوانین مدرسه": "ruleCompliance",
  "تعامل با معلمان": "teacherInteractions",
  "نیاز به نظارت ویژه": "specialSupervisionNeeds",
  "پیشنهادات انضباطی": "disciplinarySuggestions",
  "توضیحات تکمیلی معاون انضباطی": "deputyNotes",
  "نتیجه نهایی معاون انضباطی (پذیرش/عدم پذیرش)": "deputyDecision",
} as const;

export type FieldMapperKeys = keyof typeof fieldMapper;
export type FieldMapperValues = typeof fieldMapper[FieldMapperKeys];

export const reverseMapper = Object.fromEntries(
  Object.entries(fieldMapper).map(([k, v]) => [v, k])
);